name: prompts.chat
title: prompts.chat
subtitle: World's First & Most Famous Prompts Directory

github_pages:
  url: "https://vksepm.github.io/awesome-chatgpt-prompts"
  branch: "feature/ui-changes"

repository: vksepm/awesome-chatgpt-prompts