name: prompts.chat
title: prompts.chat
subtitle: World's First & Most Famous Prompts Directory

github_pages:
  url: "https://prompts.chat"
  branch: "main"

repository: f/awesome-chatgpt-prompts

baseurl: "/awesome-chatgpt-prompts"
