#!/usr/bin/env bash

curl -s https://raw.githubusercontent.com/vksepm/awesome-chatgpt-prompts/refs/heads/feature/ui-changes/prompts.csv | tail +2 | ruby -rcsv -e 'CSV.parse(STDIN.read) {|row| puts row.join("\t")}' | fzf -1 -q "$1" --with-nth 1 --delimiter "\t" --preview 'echo {2} | fold -s -w $(tput cols)' | cut -d"	" -f2
        